LPS-69775 Build soy
thiago-rocha/liferay-portal pull request #62
Opened 2017-02-02 02:46 UTC by diogo-lins

2017-02-02 18:36 UTC, thiago-rocha commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-02-02 20:33 UTC, thiago-rocha requested changes

2017-02-02 20:33 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/main/resources/META-INF/resources/grid_field.js
> -						var gridRowsNode = instance.getGridRowsNode();
Instead of access the DOM to get the selected value you can use the `value` attribute, since we guarantee the `value` is always updated.

2017-02-02 20:33 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/main/resources/META-INF/resources/grid_field.js
> +						if (!value) {
Instead of check if `!value` you could star the `value` attribute with `{}`.

2017-02-02 20:34 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/main/resources/META-INF/resources/grid_field.js
> +						return instance.focusTarget;
Since the `focusTarget` is a private element it should star with a underscore `_ focusTarget`

2017-02-02 21:11 UTC, thiago-rocha requested changes

2017-02-02 21:11 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/test/testJS/grid_field.js
> +						assert.equal(gridField.getValue().A, undefined);
Instead of check for specific values (`A`, `B`) you can just check is `getValue` returns `{}`.

2017-02-02 21:11 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/test/testJS/grid_field.js
> +					'should return object values if set an only option',
I don't understanding this test description, could you rephrase it?

2017-02-02 21:11 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/test/testJS/grid_field.js
> +						assert.equal(gridField.getValue().A, '1');
You should compare the `getValue` result with the seted value `{A: '1', B: '2'}`

2017-02-02 21:11 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/test/testJS/grid_field.js
> +							{
To make sure the value came from the context you should create the Grid using the attribute `context`
`createGridField(
  {
    context: {
      value: {B: '2'}
    }
  }
)`

2017-02-02 21:11 UTC, thiago-rocha commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/test/testJS/grid_field.js
> +					'should click in a radio input and get its value',
Add a test where a value is already set and you click in a different options to see if the value was changed

2017-02-03 14:53 UTC, diogo-lins commented on modules/apps/forms-and-workflow/dynamic-data-mapping/dynamic-data-mapping-type-grid/src/test/testJS/grid_field.js
> +						assert.equal(gridField.getValue().A, undefined);
I tried to do this way, but the compare between **{}** and **{}** always will be **false**, because two '{}' are different objects.

2017-02-03 16:31 UTC, diogo-lins commented
Updated

2017-02-03 20:10 UTC, diogo-lins commented
Updated.

2017-02-03 20:10 UTC, thiago-rocha commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-02-06 18:52 UTC, diogo-lins commented
Updated.

2017-02-06 18:58 UTC, thiago-rocha commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-02-06 19:18 UTC, thiago-rocha commented
Pull request submitted to https://github.com/ctampoya/liferay-portal/pull/71. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-02-06 19:18 UTC, closed without merging